### ISSUE TITLE
Authentication, misc

### ISSUE THREAD

**Issue by kersommoura** [PulpQE/pulp-smash#751]
[MVP Authentication](https://pulp.plan.io/projects/pulp/wiki/Pulp_3_Minimum_Viable_Product#Authentication)

~~- Disable JWT token expiration. This configuration is in the settings file and is system-wide.~~
~~- Configure the JWT tokens to expire after a configurable amount of time. This configuration is in the settings file and is system-wide.~~

The JWT shall have a username identifier.

**At the time of creating this issue, these taxed items were not confirmed in the MVP document.**

**Comment by bmbouter** [comment]
Both basic auth and JWT auth are merged. You can see their docs here: http://docs.pulpproject.org/en/3.0/nightly/integration_guide/rest_api/authentication.html

**Comment by Ichimonji10** [comment]
@kersommoura I think that this issue has been resolved. The relevant tests are documented [here](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_auth.html). Do you agree? Can we close this issue?

**Comment by kersommoura** [comment]
@Ichimonji10, I was waiting to have the full documentation in place to be able to confirm that we covered all the test cases. There are few other items listed in the MVP, and still not defined in the current version of documentation.

[Authentication](https://pulp.plan.io/projects/pulp/wiki/Pulp_3_Minimum_Viable_Product#Authentication)

For instance:

> As an API user, I can authenticate any API call (except to request a JWT) with a JWT. (not certain if this should be the behavior) [in progress]
> 
> As an API user, I can invalidate all existing JWT tokens for a given user. [done]
> 
> As an authenticated user, when deleting a user 'foo', all of user 'foo's existing JWTs are invalidated. [done]
>

**Comment by Ichimonji10** [comment]
That makes sense. There's authentication-related topics that we aren't testing.

**Comment by Ichimonji10** [comment]
We now have good test coverage for JWT tokens. The only line in the MVP that we aren't testing is this one:

> The JWT shall have a username identifier [done]

As it turns out, JWT tokens are a little tricky to decode. We could either dig into how JWT tokens and write some custom code to do this (it involves a little bit of base64 encoding/decoding trickery and possibly a little bit of encryption trickery), or we could add a dependency on a relevant library, like pyjwt, python-jose or pycrypto.

I'm in favor of just ignoring this area and declaring JWT functionality sufficiently tested. From an end user's perspective, my main concern is that JWTs work for authentication, which they do, and that I can do things like create and invalidate JWT tokens, which I can. Writing custom code for this test seems like a lot of work for little return, and adding a dependency for this one test seems like a bad trade-off.

**Comment by Ichimonji10** [comment]
This issue is fixed. See [`pulp_smash.tests.pulp3.pulpcore.api_v3.test_auth`](http://pulp-smash.readthedocs.io/en/latest/api/pulp_smash.tests.pulp3.pulpcore.api_v3.test_auth.html).
